--------------------------------------------------------
--  Fichier créé - mardi-janvier-20-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DIM_AVION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DWC"."DIM_AVION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  DDL for Table DIM_AVION
--------------------------------------------------------

  CREATE TABLE "DWC"."DIM_AVION" 
   (	"ID" NUMBER(3,0), 
	"IMM" VARCHAR2(8 CHAR), 
	"APPAREIL" VARCHAR2(8 CHAR), 
	"CAPACITE" NUMBER(3,0), 
	"TUAFF" VARCHAR2(3 CHAR), 
	"COWNER" VARCHAR2(6 CHAR), 
	"DENTREE" DATE, 
	"DSORTIE" DATE, 
	"TYPE" VARCHAR2(10 CHAR), 
	"NOWNER" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DWC"."DIM_AVION"."ID" IS 'id';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."IMM" IS 'immatriculation';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."APPAREIL" IS 'type de l''avion ce type est utilisé pour analyses commerciales non type technique de l''avion';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."CAPACITE" IS 'nombre de sièges de l''avion: so par defaut';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."TUAFF" IS '"TU" ou "AFF"
 ';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."COWNER" IS 'code de la compagnie proprietère de cette avion';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."DENTREE" IS 'date d''entrée en service de cette avion pour les avions TU';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."DSORTIE" IS 'date d''entrée en service de cette avion pour les avions TU';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."TYPE" IS 'Type technique de l''avion exp A320, A319,...';
   COMMENT ON COLUMN "DWC"."DIM_AVION"."NOWNER" IS 'nom de la compagnie proprietère de cette avion';
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DWC"."USERS" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"ENABLED" NUMBER(*,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DWC"."USERS"."USERNAME" IS 'login';
   COMMENT ON COLUMN "DWC"."USERS"."PASSWORD" IS 'mot de passe';
   COMMENT ON COLUMN "DWC"."USERS"."DESCRIPTION" IS 'matricule, first name, last name';
   COMMENT ON COLUMN "DWC"."USERS"."ENABLED" IS '1: compte actif, 0:compte non actif';
REM INSERTING into DWC.DIM_AVION
SET DEFINE OFF;
Insert into DWC.DIM_AVION (ID,IMM,APPAREIL,CAPACITE,TUAFF,COWNER,DENTREE,DSORTIE,TYPE,NOWNER) values ('2','TU-IMC','320','160','TU','TU',null,null,'A320','Tunisair');
Insert into DWC.DIM_AVION (ID,IMM,APPAREIL,CAPACITE,TUAFF,COWNER,DENTREE,DSORTIE,TYPE,NOWNER) values ('1','TU-IMO','320','162','TU','TU',null,null,'A320','Tunisair');
commit;
REM INSERTING into DWC.USERS
SET DEFINE OFF;
Insert into DWC.USERS (USERNAME,PASSWORD,DESCRIPTION,ENABLED) values ('test','test','test','1');
commit;
--------------------------------------------------------
--  DDL for Index DIM_AVION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWC"."DIM_AVION_UK1" ON "DWC"."DIM_AVION" ("IMM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIM_AVION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWC"."DIM_AVION_PK" ON "DWC"."DIM_AVION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DWC"."TABLE1_PK" ON "DWC"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DIM_AVION
--------------------------------------------------------

  ALTER TABLE "DWC"."DIM_AVION" ADD CONSTRAINT "DIM_AVION_UK1" UNIQUE ("IMM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DWC"."DIM_AVION" ADD CONSTRAINT "DIM_AVION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "DWC"."DIM_AVION" MODIFY ("IMM" NOT NULL ENABLE);
  ALTER TABLE "DWC"."DIM_AVION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DWC"."USERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DWC"."USERS" MODIFY ("ENABLED" NOT NULL ENABLE);
  ALTER TABLE "DWC"."USERS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DWC"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DWC"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger DIM_AVION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DWC"."DIM_AVION_TRG" 
BEFORE INSERT ON DIM_AVION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DIM_AVION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DWC"."DIM_AVION_TRG" ENABLE;
